### ISSUE TITLE
Add job detail page

### ISSUE THREAD

**Issue by Moeriki** [Foursevens/f7-wordpress-theme#10]
### Context

https://foursevens.be/en/jobs/digital-analyst/

### Acceptance Criteria

* Add page add `/jobs/{slug}` to list all jobs
* Fields: title, required_languages, required_skill_level, content

**Comment by naseerkassar** [comment]
Dieter the acceptance criteria have extra fields that are not needed these fields are  required_languages, required_skill_level  we only need title and content can you please recheck this ??

**Comment by Moeriki** [comment]
Correct only `title` and `content` was needed :)
