### ISSUE TITLE
social media icons 

### ISSUE THREAD

**Issue by naseerkassar** [Foursevens/f7-wordpress-theme#102]
### Steps 

1. go to https://f7-theme.moeriki.now.sh/fr/blog/rotterdam-circulair or any page have the social media icons .

2. Refresh the page .

### Expected 
Expected to have normal reaction and nothing weird to see

### Result 
When refreshed the icons appears too big for a part of second during the refresh as soon as the refresh ends it comes back normal

**Comment by Moeriki** [comment]
Relevant.

https://github.com/FortAwesome/react-fontawesome/issues/134
