### ISSUE TITLE
Case grid item height differs depending on title length

### ISSUE THREAD

**Issue by naseerkassar** [Foursevens/f7-wordpress-theme#105]
### Steps 

1. serve to https://f7-theme.moeriki.now.sh/fr/cases

### Expected 
All the cases have the same hight 

### Result 
New Case was added that have more hight than the others it is styling issue 

<img width="1423" alt="Screenshot 2019-11-12 at 13 11 44" src="https://user-images.githubusercontent.com/37541400/68670809-12401900-054e-11ea-82b8-dcc0ed1561f0.png">

**Comment by Moeriki** [comment]
Good report 👍 I changed label into UI improvement.

A bug is more for when it's really broken / unusable.

**Comment by naseerkassar** [comment]
Thanks for the information 🙂👍
