### ISSUE TITLE
Investigate the missing videos in blog page 

### ISSUE THREAD

**Issue by naseerkassar** [Foursevens/f7-wordpress-theme#99]
### steps

1. Go to https://f7-theme.moeriki.now.sh/en/blog

2. Filter for videos  

### Expected 
We expect to see any video content 

### Result
We are getting empty page

**Comment by Moeriki** [comment]
I can't reproduce an issue. Is this still the case? If so could provide a reproducible example.

**Comment by naseerkassar** [comment]
I updated the description of the bug and now it is more clear thank you for the help on how to write effective bug description

**Comment by Moeriki** [comment]
Still can't produce. Closing for now.
